workflows:
  android-release:
    name: Android APK Build
    max_build_duration: 60
    environment:
      vars:
        JAVA_VERSION: "17"
      android:
        build_version: "33"
        ndk: "25.1.8937393"
    scripts:
      - name: Clean project
        script: ./gradlew clean
      - name: Build release APK
        script: ./gradlew assembleRelease
    artifacts:
      - app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - "your-email@example.com"
